### PR TITLE
Simplify local setup using docker

### LINKED ISSUE #8: Update dependencies, refactor routes and event broadcasters
- [x] Update dependencies according to new release.
- [x] Move `broadcasting` routes under `routes/web.php` to `routes/api.php`
- [x] Add throttling for `public-message` route, add user auth check for other routes using middlewares.
- [x] Rename `events/PresenceMessageNotification.php` to `events/PresenceMessageEvent.php`.
- [x] Rename `events/PrivateMessageNotification.php` to `events/PrivateMessageEvent.php`.
- [x] Rename `events/PublicMessageNotification.php` to `events/PublicMessageEvent.php`.
- [x] Fix `broadcastOn` as per doc.
- [x] Rename classes the same as the file name.
- [x] Dockerize app. for easy setup and running.
- [ ] Improve SEO of the repository, by updating to proper description and labels.

### PR DESCRIPTION
**Pull request by qsdstefan**
- Added `docker-compose` with 2 services
 1. Backend - Uses laravel base image to install dependencies and start the laravel server, serving real-time build from frontend.  
 2. Frontend- Installs npm dependencies and starts hot-reload service to generate a build.
 - Updated README
 
- Fixed #8

### CODE REVIEW

**Comment by sacOO7** [comment]
Please add steps to run demo app using docker

**Review by sacOO7 — COMMENTED** [review]
Please add commands to README to run demo app using docker.
Below setup, section can be added 
`Setup using docker`, this will help with running the app using docker.

**Review by sacOO7 — COMMENTED** [review]
When using docker-compose, dockerfile should only contain command to install dependencies.
Please create 2 services under `docker-compose`, one for `php artisan start`  and another for `npm  run watch`

**Review by sacOO7 — COMMENTED** [review]
Use stable laravel base image instead of installing dependencies manually. 
https://hub.docker.com/r/bitnami/laravel/ seems to be popular

**Review by owenpearson — APPROVED** [review]
Looks fine, you might wanna rename the dockerfiles to `backend.dockerfile` and `frontend.dockerfile` since most editors will use that extension to determine filetype for syntax highlighting

**Pull request merged**
