### PR TITLE
Readme instruction order

### PR DESCRIPTION
**Pull request by AndyTWF**
Changes the order of instructions in the README to avoid the issue encountered in https://github.com/ably-labs/laravel-broadcast-app/issues/15

### CODE REVIEW

**Comment by sacOO7** [comment]
@AndyTWF we also need to update the section https://github.com/ably-labs/laravel-broadcast-app#run-using-docker as per change in steps.

**Review by sacOO7 — CHANGES_REQUESTED** [review]
Update - Run using docker section - 
Clone the repo. and set [ABLY_KEY](https://faqs.ably.com/setting-up-and-managing-api-keys) as mentioned in step **2 and 3** of [SETUP](https://github.com/ably-labs/laravel-broadcast-app#setup).

**Comment by AndyTWF** [comment]
> @AndyTWF we also need to update the section https://github.com/ably-labs/laravel-broadcast-app#run-using-docker as per change in steps.

Done!

**Review by sacOO7 — APPROVED** [review]
LGTM : )

**Pull request merged**
